---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    app: reddit
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "reddit-mongo-data"
