version: '3.3'

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
  post:
    image: ${DOCKERHUB_USERNAME}/post:${POST_VERSION}
    depends_on: ['mongo']
  comment:
    image: ${DOCKERHUB_USERNAME}/comment:${COMMENT_VERSION}
    depends_on: ['mongo']
  ui:
    image: ${DOCKERHUB_USERNAME}/ui:${UI_VERSION}
    ports:
      - "${UI_PORT}:9292/tcp"
    depends_on: ['post', 'comment']
  prometheus:
    image: ${DOCKERHUB_USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"

volumes:
  mongo_data: {}
