version: '3.3'

services:

  mongo:
    image: mongo:${MONGO_VERSION}
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    depends_on: ['mongo']

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    depends_on: ['mongo']

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - "${UI_PORT}:9292/tcp"
    depends_on: ['post', 'comment']

  prometheus:
    image: ${USER_NAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - "${PROMETHEUS_PORT}:9090"

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb-exporter:
    image: ${USER_NAME}/mongodb_exporter:${MONGO_EXPORTER_VERSION}
    environment:
      - MONGODB_URL=mongodb://mongo:27017

  blackbox-exporter:
    image: ${USER_NAME}/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}
    command: '--config.file=/config/blackbox.yml'
    ports:
      - "${BLACKBOX_EXPORTER_PORT}:9115"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

volumes:
  mongo_data: {}
