version: '3.3'

services:

  mongo:
    networks:
      back_net:
        aliases:
          - prod.db.acme.com

  post:
    env_file:
      - .env.prod

  ui:
    environment:
      - ENV=PRODUCTION

  comment:
    env_file:
      - .env.prod

  portainer:
    image: portainer/portainer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    networks:
      - back_net

volumes:
  portainer_data: {}
