---
# ------------------- Post Nework Policy ------------------- #
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: post-access
  labels:
    app: reddit
spec:
  podSelector:
    matchLabels:
      app: reddit
      component: post
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: reddit
          component: ui
    ports:
      - protocol: TCP
        port: 5000
