{{- if and .Values.pagesExternalScheme .Values.pagesExternalDomain}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-pages
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  {{- if .Values.pagesTlsSecret }}
  tls:
  - hosts:
    - "*.{{ .Values.pagesExternalDomain }}"
    secretName: {{ .Values.pagesTlsSecret }}
  {{- end }}
  rules:
  - host: "*.{{ .Values.pagesExternalDomain }}"
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "fullname" . }}
            servicePort: 8090
{{- end }}
---
