---
# ------------------- Post Deployment ------------------- #
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "post.fullname" . }}
  labels:
    app: reddit
    component: post
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: reddit
      component: post
      release: {{ .Release.Name }}
  replicas: 3
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: post
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: post
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: post
            protocol: TCP
        env:
        - name: POST_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
